### ISSUE TITLE
Browser detects virus in i386 Windows file

### ISSUE THREAD

**Issue by FreakwaveCGN** [plantimals/2vcf#15]
Edge and Chrome browsers detect a virus in the most recent version, i386 Windows file.

**Comment by plantimals** [comment]
I think this is likely just the fact that it's i386 and not x86_64 being used as heuristic. I'm just going to remove the i386 builds, as I don't think they are useful for anyone. 

For the moment, would you mind trying the x86_64 binary and letting me know if you see the same thing?

**Comment by plantimals** [comment]
ok, I've created a new release without the i386 options: https://github.com/plantimals/2vcf/releases/tag/v0.4.1 

thanks for taking the time to let me know about this @FreakwaveCGN

**Comment by FreakwaveCGN** [comment]
Thanks Rob, I could download it without a problem now 👍
Is it possible to run this on a Windows machine? I'm not a coder, but it looks to me that the commands you're using are UNIX specific... Thanks!

**Comment by plantimals** [comment]
Yes, you should be able to run the executable in the shell. you'll need to open the shell, change directories `cd c:\path\to\download\folder` and run it `2vcf.exe --ref c:\path\to\ref --input c:\path\to\raw-data`, or something to that effect.  please report back if you have any troubles. thanks again for your report.
