### ISSUE TITLE
VCF 4.0 to 4.2

### ISSUE THREAD

**Issue by gkatagi** [plantimals/2vcf#22]
Hi,
Thanks for providing updated reference file (db151). While the conversion is complete, the output vcf seems to be in 4.0 version. However, the latest version and widely used VCF file format seems to be 4.2 or in some cases 4.3.
Can you please let me know how to get VCF file in 4.2 format ?

**Comment by plantimals** [comment]
hi @gkatagi , which specific features of the 4.2 format you require? or at least which parser you care about passing? `2vcf` outputs inherit the `VCFv4.0` version from the source dbSNP VCF. Also, thanks for your feedback.

**Comment by gkatagi** [comment]
Hi,
I am concerned about genotype information in the files which needs to be used for GWAS or any of downstream analysis..

**Comment by plantimals** [comment]
I'm happy to help advise in any way I can, but I don't know enough about your use case to really help. I you have a specific concern, please let me know.
