### ISSUE TITLE
Support for files with build36

### ISSUE THREAD

**Issue by gkatagi** [plantimals/2vcf#23]
Hi 
I happen to come across few 23andme files which are generated way back in 2011.  The header section of the files mentions that they are using reference human genome assembly build 36 for genotype calls.  There are two approaches which we can work with these files.  (1) make a liftover of these coordinates to hg19 and then call 2vcf program  (2) make a reference vcf file for the build 36 , convert it VCF with 2vcf and then a make a liftOver. ?   Can you please let me know which approach is better and how can we do it ?  If you can the update the method and the relevant files, that would be great..  Thanks

**Comment by plantimals** [comment]
I can't answer to "which approach is better", as I do not know what your use case is. I am happy to advise if you want to describe your use here in enough detail.
