### ISSUE TITLE
http://openb.io/2vcf/2vcf-v2.0.vcf.gz not accessible

### ISSUE THREAD

**Issue by ravelab** [plantimals/2vcf#24]

**Comment by a4xrbj1** [comment]
Rob, any update on this? Seems the whole http://openb.io URL is broken. Thank you!

**Comment by HolyOne** [comment]
I am having the same problem

**Comment by plantimals** [comment]
apologies, but at some point in the past my registration of openb.io lapsed. I have moved the files in question to the same paths, but under the `https://plantimals.org` domain. so the above mentioned file is now at `https://plantimals.org/2vcf/2vcf-v2.0.vcf.gz`.
